before:
  hooks:
    - go mod tidy
builds:
  - id: "equalizer"
    main: ./cmd/main.go
    binary: equalizer
    ldflags:
      - -s -w -X main.VERSION=v{{.Version}}
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=arenas
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    hooks:
      post:
       # - upx "{{ .Path }}"

archives:
  - id: "equalizer"
    builds:
      - "equalizer"
    format: binary
    name_template: >-
      giserver_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
